### ISSUE TITLE
Saving tree to file

### ISSUE THREAD

**Issue by arnauqb** [rdeits/RegionTrees.jl#29]
Thanks for this amazing package. It has been very useful for my research.
I do not know if this is the appropriate space to ask this, but, how can I save the state of the quadtree to a file to read it later? I have tried using the JLD.jl package but I get a StackOverflowError, I guess because it has problems dealing with the Cell type?

 Any help would be appreciated.

**Comment by rdeits** [comment]
Thanks! I'm glad it's been useful. 

I think you should be able to use JLD2.jl for this. Here's a very simple example:

```julia
julia> using RegionTrees

julia> using StaticArrays

julia> cell = Cell(SVector(-1., -2, -3), SVector(2., 4, 6), 0)
uCell: HyperRectangle{3,Float64}([-1.0, -2.0, -3.0], [2.0, 4.0, 6.0])

julia> using JLD2

julia> @save "cell.jld2" cell
```

(in a new Julia session):

```julia
julia> using RegionTrees

julia> using JLD2

julia> @load "cell.jld2" cell
1-element Array{Symbol,1}:
 :cell

julia> cell.boundary
HyperRectangle{3,Float64}([-1.0, -2.0, -3.0], [2.0, 4.0, 6.0])
```

**Comment by arnauqb** [comment]
It works, thanks!
