### ISSUE TITLE
Move to JuliaGeometry?

### ISSUE THREAD

**Issue by juliohm** [rdeits/RegionTrees.jl#44]
Hi @rdeits , thank you for this package. Would you be interested in moving it to JuliaGeometry for greater visibility? We are considering wrapping it in Meshes.jl as a new dependency.

**Comment by juliohm** [comment]
ping @rdeits

**Comment by rdeits** [comment]
Whoops, sorry--I still haven't figured out how to balance parenting and keeping my open source up to date. I think this is a great idea if you're still interested.

**Comment by juliohm** [comment]
I see you are a member of JuliaGeometry already. Can you move the repo? Let me know if you need help.

**Comment by juliohm** [comment]
Solved.

**Comment by cserteGT3** [comment]
The General registry requires (but does not enforce) to update the repo URL after moving packages (described in its [Readme](https://github.com/JuliaRegistries/General#how-do-i-transfer-a-package-to-an-organization-or-another-user)). https://github.com/JuliaRegistries/General/pull/159992 addresses this to finish the transfer.
